dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
   - curl -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uyehorka9991:$BINTRAY_API_KEY https://api.bintray.com/content/yehorka9991/homework/homework_1/$TRAVIS_BUILD_NUMBER/cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
